org.gradle.jvmargs=-Xmx2048m -XX:+UseParallelGC -XX:TieredStopAtLevel=1 -Dorg.gradle.daemon.instrumentation=false -Xshare:off -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx1536m -XX:+UseParallelGC -XX:TieredStopAtLevel=1 -Xshare:off
org.gradle.daemon.instrumentation=false
kotlin.incremental=false
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=36
ksp.incremental=false
ksp.useKSP2=false
