package com.alfanewgen.galpika.ui.screens.profile

import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.Send
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.alfanewgen.galpika.data.model.Grievance
import com.alfanewgen.galpika.data.repository.NewsRepository
import com.alfanewgen.galpika.theme.*
import kotlinx.coroutines.launch

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun GrievanceScreen(
    newsRepository: NewsRepository,
    onBack: () -> Unit
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    var name by remember { mutableStateOf("") }
    var email by remember { mutableStateOf("") }
    var phone by remember { mutableStateOf("") }
    var articleInfo by remember { mutableStateOf("") }
    var reason by remember { mutableStateOf("కంటెంట్ అభ్యంతరం") }
    var description by remember { mutableStateOf("") }
    var isSubmitting by remember { mutableStateOf(false) }
    var ticketGenerated by remember { mutableStateOf<String?>(null) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        text = "ఫిర్యాదుల పరిష్కారం (Grievance Redressal)",
                        fontFamily = RamabhadraFont,
                        fontSize = 17.sp,
                        color = Color.White
                    )
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(imageVector = Icons.Default.ArrowBack, contentDescription = "వెనుకకు", tint = Color.White)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = PrimaryBlue)
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .background(BackgroundLight)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(14.dp)
        ) {
            // Statutory Notice Box under IT Rules 2021
            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(10.dp),
                colors = CardDefaults.cardColors(containerColor = SurfaceVariant),
                border = CardDefaults.outlinedCardBorder().copy(brush = androidx.compose.ui.graphics.SolidColor(PrimaryBlue))
            ) {
                Column(modifier = Modifier.padding(14.dp)) {
                    Text(
                        text = "భారతీయ IT చట్టం (Intermediary Guidelines) 2021 నిబంధనలు",
                        fontFamily = RamabhadraFont,
                        fontSize = 15.sp,
                        fontWeight = FontWeight.Bold,
                        color = PrimaryBlue
                    )
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                        text = "ఈ పోర్టల్‌లోని ఏదైనా వ్యంగ్య కథనం లేదా అంశంపై అభ్యంతరం ఉంటే, ఇక్కడ ఫిర్యాదు చేయవచ్చు. మా గ్రీవెన్స్ ఆఫీసర్ 24 గంటలలోపు రసీదు ఇచ్చి, 15 రోజుల్లోగా సమస్యను పరిష్కరిస్తారు.\n\nగ్రీవెన్స్ ఆఫీసర్: శ్రీహరి రావు\nఈమెయిల్: grievance@galpika.com",
                        fontFamily = MallannaFont,
                        fontSize = 13.sp,
                        lineHeight = 20.sp,
                        color = TextSecondary
                    )
                }
            }

            if (ticketGenerated != null) {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(10.dp),
                    colors = CardDefaults.cardColors(containerColor = Color(0xFFDCFCE7))
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text(
                            text = "✅ ఫిర్యాదు విజయవంతంగా నమోదైంది!",
                            fontFamily = RamabhadraFont,
                            fontWeight = FontWeight.Bold,
                            fontSize = 16.sp,
                            color = Color(0xFF166534)
                        )
                        Spacer(modifier = Modifier.height(6.dp))
                        Text(
                            text = "మీ టికెట్ నంబర్: $ticketGenerated\n24 గంటల్లో మా గ్రీవెన్స్ ఆఫీసర్ పరిశీలించి మీకు ఇమెయిల్ ద్వారా తెలియజేస్తారు.",
                            fontFamily = MallannaFont,
                            fontSize = 14.sp,
                            color = Color(0xFF15803D)
                        )
                    }
                }
            } else {
                OutlinedTextField(
                    value = name,
                    onValueChange = { name = it },
                    label = { Text("మీ పూర్తి పేరు (Full Name)", fontFamily = MallannaFont) },
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(10.dp)
                )

                OutlinedTextField(
                    value = email,
                    onValueChange = { email = it },
                    label = { Text("ఇమెయిల్ చిరునామా (Email Address)", fontFamily = MallannaFont) },
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(10.dp)
                )

                OutlinedTextField(
                    value = phone,
                    onValueChange = { phone = it },
                    label = { Text("ఫోన్ నంబర్ (ఐచ్ఛికం)", fontFamily = MallannaFont) },
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(10.dp)
                )

                OutlinedTextField(
                    value = articleInfo,
                    onValueChange = { articleInfo = it },
                    label = { Text("వార్త శీర్షిక లేదా లింక్ (Article Title/URL)", fontFamily = MallannaFont) },
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(10.dp)
                )

                OutlinedTextField(
                    value = description,
                    onValueChange = { description = it },
                    label = { Text("సమస్య లేదా అభ్యంతరం పూర్తి వివరాలు", fontFamily = MallannaFont) },
                    placeholder = { Text("కథనంలో ఏ విషయానికి సంబంధించి అభ్యంతరం వ్యక్తం చేస్తున్నారో స్పష్టంగా వివరించండి...", fontFamily = MallannaFont) },
                    modifier = Modifier.fillMaxWidth(),
                    minLines = 4,
                    shape = RoundedCornerShape(10.dp)
                )

                Button(
                    onClick = {
                        if (name.isBlank() || email.isBlank() || description.isBlank()) {
                            Toast.makeText(context, "పేరు, ఈమెయిల్ మరియు సమస్య వివరాలు తప్పనిసరి!", Toast.LENGTH_SHORT).show()
                            return@Button
                        }
                        isSubmitting = true
                        scope.launch {
                            val gr = Grievance(
                                complainantName = name,
                                email = email,
                                phone = phone,
                                articleUrlOrTitle = articleInfo,
                                complaintReason = reason,
                                description = description
                            )
                            val res = newsRepository.submitGrievance(gr)
                            isSubmitting = false
                            if (res.isSuccess) {
                                ticketGenerated = res.getOrNull()
                            } else {
                                Toast.makeText(context, "ఎర్రర్: ${res.exceptionOrNull()?.message}", Toast.LENGTH_SHORT).show()
                            }
                        }
                    },
                    modifier = Modifier.fillMaxWidth(),
                    enabled = !isSubmitting,
                    colors = ButtonDefaults.buttonColors(containerColor = PrimaryBlue),
                    shape = RoundedCornerShape(10.dp)
                ) {
                    if (isSubmitting) {
                        CircularProgressIndicator(color = Color.White, modifier = Modifier.size(22.dp))
                    } else {
                        Icon(imageVector = Icons.Default.Send, contentDescription = null)
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(text = "ఫిర్యాదును సమర్పించండి (Submit Grievance)", fontFamily = MallannaFont, fontSize = 16.sp)
                    }
                }
            }
        }
    }
}
